name: Projekt News-Stream Archiv
description: Gefördert vom BMBF, 2015-2017 
meta_description: "Website siehe newsstreamproject.org"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /newsstream-archiv
domain_name: 'http://dpa-newslab.github.io'
google_analytics: 
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
